// Server-only Hypixel + Mojang API access.

import { decodeNbt, type NbtValue } from "./nbt.server";
import {
  computePetLevel,
  computeSkill,
  SKILL_META,
  titleCase,
  type AuctionEntry,
  type BazaarProduct,
  type InventoryContainer,
  type InventoryItem,
  type LiveItem,
  type PlayerData,
  type ProfileSummary,
  type SkillKey,
  type WikiAbility,
  type WikiRecipe,
  type WikiRequirement,
} from "./skyblock";
import { validatePlayerData, type PlayerDataValidated } from "./schemas";
// Recipes sourced from the NotEnoughUpdates repo (the Hypixel items endpoint
// no longer includes them). Generated by `bun scripts/generate-recipes.mjs`.
import generatedRecipes from "./items/generated-recipes.json";
// Extra per-item data (crafting grid, canonical wiki URL, craft text).
import generatedExtras from "./items/generated-items-extra.json";

export type ItemExtra = {
  grid?: Record<string, string | number>;
  wikiUrl?: string;
  craftText?: string;
  displayName?: string;
  lore?: string[];
  stats?: Record<string, number>;
  requirements?: Array<{
    type: string;
    level?: number;
  }>;
  abilities?: Array<{
    name: string;
    desc: string;
    manaCost?: number;
    cooldown?: number;
  }>;
};

const ITEM_EXTRAS = generatedExtras as unknown as Record<string, ItemExtra>;

const API = "https://api.hypixel.net/v2";

export class HypixelError extends Error {}

// ============================================================================
// OPERATOR KEY POOL
//
// Profile endpoints need an API key. Users can supply their own (BYOK); when
// they don't, we fall back to the operator's shared pool. Accepts a
// comma-separated list so a regenerated/expired key never takes the site
// down — dead keys are skipped automatically and retried after a cooldown.
// ============================================================================

const keyCooldowns = new Map<string, number>(); // key -> ms timestamp when retry is allowed
let keyCursor = 0;

export function getOperatorKeys(): string[] {
  return (process.env["HYPIXEL_API_KEY"] ?? "")
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);
}

function nextOperatorKey(): string | null {
  const now = Date.now();
  const keys = getOperatorKeys().filter((k) => (keyCooldowns.get(k) ?? 0) < now);
  if (!keys.length) return null;
  const key = keys[keyCursor % keys.length]!;
  keyCursor++;
  return key;
}

function markKeyFailed(key: string): void {
  // Cool the key down for 10 minutes before trying it again.
  keyCooldowns.set(key, Date.now() + 10 * 60_000);
}

/** Coarse health of the shared profile pool, for the footer indicator. */
export function profileApiHealth(): "ok" | "degraded" | "no-key" {
  const keys = getOperatorKeys();
  if (!keys.length) return "no-key";
  return keys.some((k) => (keyCooldowns.get(k) ?? 0) < Date.now()) ? "ok" : "degraded";
}

// ============================================================================
// PROFILE CACHE
// ============================================================================

const profileCache = new Map<string, { at: number; data: unknown }>();
const PROFILE_CACHE_TTL = 90_000;
const uuidCache = new Map<string, { uuid: string; name: string }>();

// ============================================================================
// GENERIC FETCH
// ============================================================================

async function getJson<T>(url: string, apiKey?: string): Promise<T | null> {
  try {
    const res = await fetch(url, {
      headers: apiKey ? { "API-Key": apiKey } : {},
    });

    const text = await res.text();

    let body: unknown;

    try {
      body = JSON.parse(text);
    } catch {
      console.error(`Unexpected response from Hypixel (${res.status})`);
      return null;
    }

    const payload = body as {
      success?: boolean;
      cause?: string;
    };

    if (!res.ok || payload.success === false) {
      console.warn(`Hypixel request failed (${res.status}): ${payload.cause ?? "Unknown"}`);
      return null;
    }

    return body as T;
  } catch (err) {
    console.error(`Network fetch failed for ${url}:`, err);
    return null;
  }
}

/**
 * Fetch a keyed endpoint using the user's key when provided, otherwise the
 * operator pool with automatic failover between keys.
 */
async function getKeyedJson<T>(url: string, userKey?: string): Promise<T | null> {
  if (userKey) {
    return getJson<T>(url, userKey);
  }
  const tried = new Set<string>();
  for (;;) {
    const key = nextOperatorKey();
    if (!key || tried.has(key)) return null;
    tried.add(key);
    const result = await getJson<T>(url, key);
    if (result !== null) return result;
    // Likely an auth/quota failure on this key — cool it down and try the next.
    markKeyFailed(key);
  }
}

// ============================================================================
// SECOND-TIER ENDPOINTS — guild, status, friends, bank, election, news
// ============================================================================

export type GuildInfo = {
  name: string;
  tag: string | null;
  level: number;
  rank: string | null;
  members: number;
};

export async function getGuild(uuid: string): Promise<GuildInfo | null> {
  const data = await getKeyedJson<{
    guild?: {
      name?: string;
      tag?: string | null;
      members?: Array<{ rank?: string; uuid?: string }>;
      exp?: number;
      level?: number;
    };
  }>(`${API}/guild?player=${uuid}`);
  const guild = data?.guild;
  if (!guild?.name) return null;
  return {
    name: guild.name,
    tag: guild.tag ?? null,
    level: Number(guild.level ?? 0),
    rank: guild.members?.find((m) => m.uuid === uuid)?.rank ?? null,
    members: guild.members?.length ?? 0,
  };
}

export type PlayerStatus = {
  online: boolean;
  game?: string;
  mode?: string;
};

export async function getStatus(uuid: string): Promise<PlayerStatus | null> {
  const data = await getKeyedJson<{
    session?: { online?: boolean; gameType?: string; mode?: string };
  }>(`${API}/status?uuid=${uuid}`);
  const session = data?.session;
  if (!session) return null;
  return {
    online: Boolean(session.online),
    ...(session.gameType ? { game: session.gameType } : {}),
    ...(session.mode ? { mode: session.mode } : {}),
  };
}

export async function getFriendsCount(uuid: string): Promise<number | null> {
  const data = await getKeyedJson<{ records?: unknown[] }>(`${API}/friends?uuid=${uuid}`);
  return Array.isArray(data?.records) ? data!.records!.length : null;
}

export type BankTransactions = {
  balance: number | null;
  transactions: Array<{ amount: number; timestamp: number; action: string }>;
};

export async function getBankTransactions(uuid: string): Promise<BankTransactions | null> {
  const data = await getKeyedJson<{
    balance?: number;
    transactions?: Array<{
      amount?: number;
      timestamp?: string | number;
      action?: string;
    }>;
  }>(`${API}/skyblock/bank?uuid=${uuid}`);
  if (!data) return null;
  return {
    balance: typeof data.balance === "number" ? data.balance : null,
    transactions: (data.transactions ?? []).slice(0, 10).map((t) => ({
      amount: Number(t.amount ?? 0),
      timestamp: typeof t.timestamp === "string" ? Number(t.timestamp) : Number(t.timestamp ?? 0),
      action: String(t.action ?? "UNKNOWN"),
    })),
  };
}

// --- Global resources (site-wide, long cache) -------------------------------

let electionCache: { at: number; data: unknown } | null = null;

export async function getElection(): Promise<{
  mayor?: { name?: string; key?: string; perks?: Array<{ name?: string; description?: string }> };
  candidates?: Array<{ name?: string; perks?: Array<{ name?: string }> }>;
  year?: number;
} | null> {
  if (electionCache && Date.now() - electionCache.at < 30 * 60_000) {
    return electionCache.data as never;
  }
  const data = await getJson<Record<string, unknown>>(`${API}/resources/skyblock/election`);
  if (!data) return null;
  const result = {
    ...(data["mayor"]
      ? {
          mayor: data["mayor"] as {
            name?: string;
            key?: string;
            perks?: Array<{ name?: string; description?: string }>;
          },
        }
      : {}),
    ...(Array.isArray(data["candidates"])
      ? {
          candidates: data["candidates"] as Array<{
            name?: string;
            perks?: Array<{ name?: string }>;
          }>,
        }
      : {}),
    ...(typeof data["year"] === "number" ? { year: data["year"] as number } : {}),
  };
  electionCache = { at: Date.now(), data: result };
  return result;
}

let newsCache: { at: number; data: unknown } | null = null;

export async function getNews(): Promise<
  Array<{ title?: string; text?: string; date?: string; link?: string }>
> {
  if (newsCache && Date.now() - newsCache.at < 60 * 60_000) {
    return newsCache.data as never;
  }
  const data = await getJson<{ items?: Array<Record<string, unknown>> }>(
    `${API}/resources/skyblock/news`,
  );
  const items = (data?.["items"] ?? []).flatMap((item) => {
    const rec = item as Record<string, unknown>;
    const out: Array<{ title?: string; text?: string; date?: string; link?: string }> = [{}];
    if (typeof rec["title"] === "string") out[0]!.title = rec["title"];
    if (typeof rec["text"] === "string") out[0]!.text = rec["text"];
    const dateObj = rec["date"] as { date?: string } | undefined;
    if (typeof dateObj?.["date"] === "string") out[0]!.date = dateObj["date"];
    if (typeof rec["link"] === "string") out[0]!.link = rec["link"];
    return out[0]!.title ? [out[0]!] : [];
  });
  newsCache = { at: Date.now(), data: items };
  return items;
}

let fireSaleCache: { at: number; data: unknown } | null = null;

export async function getFireSale(): Promise<
  Array<{ item_id?: string; start?: number; end?: number }>
> {
  if (fireSaleCache && Date.now() - fireSaleCache.at < 30 * 60_000) {
    return fireSaleCache.data as never;
  }
  const data = await getJson<{ sales?: Array<Record<string, unknown>> }>(
    `${API}/resources/skyblock/fire_sale`,
  );
  const sales = (data?.["sales"] ?? []).flatMap((sale) => {
    const rec = sale as Record<string, unknown>;
    const out: Array<{ item_id?: string; start?: number; end?: number }> = [{}];
    if (typeof rec["item_id"] === "string") out[0]!.item_id = rec["item_id"];
    if (typeof rec["start"] === "number") out[0]!.start = rec["start"];
    if (typeof rec["end"] === "number") out[0]!.end = rec["end"];
    return out[0]!.item_id ? [out[0]!] : [];
  });
  fireSaleCache = { at: Date.now(), data: sales };
  return sales;
}

// --- Official XP/tier tables (accuracy upgrade over hardcoded tables) -------

let officialSkillsCache: { at: number; data: unknown } | null = null;

export async function getOfficialSkillTables(): Promise<Record<
  string,
  { maxLevel?: number; levels?: number[] }
> | null> {
  if (officialSkillsCache && Date.now() - officialSkillsCache.at < 24 * 60 * 60_000) {
    return officialSkillsCache.data as never;
  }
  const data = await getJson<{
    skills?: Record<string, { maxLevel?: number; levels?: number[] }>;
  }>(`${API}/resources/skyblock/skills`);
  if (!data?.skills) return null;
  officialSkillsCache = { at: Date.now(), data: data.skills };
  return data.skills;
}

let officialCollectionsCache: { at: number; data: unknown } | null = null;

export async function getOfficialCollectionTiers(): Promise<Record<
  string,
  { tiers?: number[] }
> | null> {
  if (officialCollectionsCache && Date.now() - officialCollectionsCache.at < 24 * 60 * 60_000) {
    return officialCollectionsCache.data as never;
  }
  const data = await getJson<{
    collections?: Record<string, { tiers?: number[] }>;
  }>(`${API}/resources/skyblock/collections`);
  if (!data?.collections) return null;
  officialCollectionsCache = { at: Date.now(), data: data.collections };
  return data.collections;
}

// ============================================================================
// UUID
// ============================================================================

export async function resolveUuid(
  username: string,
): Promise<{ uuid: string; name: string } | null> {
  try {
    const clean = username.trim().replace(/-/g, "");

    if (/^[0-9a-f]{32}$/i.test(clean)) {
      return {
        uuid: clean,
        name: username,
      };
    }

    // UUIDs never change — cache forever.
    const cached = uuidCache.get(username.trim().toLowerCase());
    if (cached) return cached;

    const res = await fetch(
      `https://api.mojang.com/users/profiles/minecraft/${encodeURIComponent(username.trim())}`,
    );

    if (res.ok) {
      const data = (await res.json()) as {
        id: string;
        name: string;
      };

      if (data?.id) {
        const resolved = {
          uuid: data.id,
          name: data.name,
        };
        uuidCache.set(username.trim().toLowerCase(), resolved);
        return resolved;
      }
    }

    const fallback = await fetch(
      `https://playerdb.co/api/player/minecraft/${encodeURIComponent(username.trim())}`,
    );

    if (fallback.ok) {
      const data = (await fallback.json()) as {
        data?: {
          player?: {
            raw_id?: string;
            username?: string;
          };
        };
      };

      const raw = data?.data?.player?.raw_id;

      if (raw) {
        const resolved = {
          uuid: raw,
          name: data.data?.player?.username ?? username,
        };
        uuidCache.set(username.trim().toLowerCase(), resolved);
        return resolved;
      }
    }
  } catch (err) {
    console.error("Failed to resolve UUID:", err);
  }

  return null;
}

// ============================================================================
// ITEM RESOURCE
// ============================================================================

type RawAbility = {
  name?: string;
  description?: string | string[];
  mana_cost?: number;
  cooldown?: number;
};

type RawRequirement = {
  type?: string;
  level?: number;
  value?: string;
  [key: string]: unknown;
};

type RawRecipe = {
  [key: string]: unknown;
};

type ItemsResponse = {
  items: Array<{
    id: string;
    name: string;
    material?: string;
    tier?: string;
    category?: string;
    npc_sell_price?: number;
    stats?: Record<string, number>;
    description?: string;
    lore?: string[];
    abilities?: RawAbility[];
    requirements?: RawRequirement[];
    recipe?: RawRecipe;
    [key: string]: unknown;
  }>;
};

export type WikiMarketData = {
  bazaar?: {
    buyPrice: number;
    sellPrice: number;
    buyVolume: number;
    sellVolume: number;
    buyMovingWeek: number;
    sellMovingWeek: number;
    buyOrders: number;
    sellOrders: number;
  };

  auctionHouse?: {
    lowestBin: number | null;
    averageBin: number | null;
    medianBin: number | null;
    listings: number;
  };

  museumValue?: number | null;
  historicalPrice?: number | null;
  demand?: number | null;
  volume?: number | null;
};

export type WikiItem = LiveItem & WikiMarketData;

let itemsCache: {
  at: number;
  items: WikiItem[];
} | null = null;

// ============================================================================
// ITEM HELPERS
// ============================================================================

function cleanText(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }

  return value.replace(/§./g, "").trim();
}

function normalizeDescription(value: string | string[] | undefined): string | string[] | undefined {
  if (typeof value === "string") {
    const cleaned = cleanText(value);
    return cleaned || undefined;
  }

  if (Array.isArray(value)) {
    const lines = value.map((line) => cleanText(line)).filter(Boolean);

    return lines.length ? lines : undefined;
  }

  return undefined;
}

function normalizeRequirements(
  requirements: RawRequirement[] | undefined,
): WikiRequirement[] | undefined {
  if (!Array.isArray(requirements)) {
    return undefined;
  }

  const normalized = requirements
    .map((req) => {
      if (!req || typeof req !== "object") {
        return null;
      }

      const type =
        typeof req.type === "string" ? titleCase(req.type.replace(/_/g, " ")) : "Requirement";

      const level = typeof req.level === "number" ? req.level : undefined;

      const value = typeof req.value === "string" ? req.value : undefined;

      return {
        type,
        ...(level !== undefined ? { level } : {}),
        ...(value !== undefined ? { value } : {}),
      };
    })
    .filter((req): req is WikiRequirement => req !== null);

  return normalized.length ? normalized : undefined;
}

function normalizeAbilities(abilities: RawAbility[] | undefined): WikiAbility[] | undefined {
  if (!Array.isArray(abilities)) {
    return undefined;
  }

  const normalized = abilities
    .filter((ability): ability is RawAbility => !!ability && typeof ability === "object")
    .map((ability) => ({
      name: cleanText(ability.name) || "Ability",

      description:
        typeof ability.description === "string"
          ? cleanText(ability.description)
          : Array.isArray(ability.description)
            ? ability.description.map(cleanText).filter(Boolean)
            : "",

      ...(typeof ability.mana_cost === "number" ? { manaCost: ability.mana_cost } : {}),

      ...(typeof ability.cooldown === "number" ? { cooldown: ability.cooldown } : {}),
    }));

  return normalized.length ? normalized : undefined;
}

// The Hypixel resource response contains recipe information on some items.
// Its exact structure has changed over time, so normalize the common forms
// without assuming every item has a recipe.
function normalizeRecipe(recipe: RawRecipe | undefined): WikiRecipe | undefined {
  if (!recipe || typeof recipe !== "object") {
    return undefined;
  }

  const ingredients: Array<{
    id: string;
    name: string;
    amount: number;
  }> = [];

  const pushIngredient = (id: string, amount: number) => {
    if (!id || !Number.isFinite(amount) || amount <= 0) {
      return;
    }

    ingredients.push({
      id,
      name: titleCase(id),
      amount,
    });
  };

  const rawIngredients = recipe["ingredients"];

  if (Array.isArray(rawIngredients)) {
    for (const ingredient of rawIngredients) {
      if (!ingredient || typeof ingredient !== "object") {
        continue;
      }

      const obj = ingredient as Record<string, unknown>;

      const id =
        typeof obj["id"] === "string"
          ? obj["id"]
          : typeof obj["item_id"] === "string"
            ? obj["item_id"]
            : undefined;

      const amount =
        typeof obj["amount"] === "number"
          ? obj["amount"]
          : typeof obj["count"] === "number"
            ? obj["count"]
            : 1;

      if (id) {
        pushIngredient(id, amount);
      }
    }
  }

  // Some Hypixel recipe structures use a simple ID -> quantity map.
  if (rawIngredients && typeof rawIngredients === "object" && !Array.isArray(rawIngredients)) {
    for (const [id, amount] of Object.entries(rawIngredients as Record<string, unknown>)) {
      if (typeof amount === "number") {
        pushIngredient(id, amount);
      }
    }
  }

  if (!ingredients.length) {
    return undefined;
  }

  const craftingType =
    typeof recipe["crafting_type"] === "string"
      ? titleCase(String(recipe["crafting_type"]))
      : typeof recipe["type"] === "string"
        ? titleCase(String(recipe["type"]))
        : undefined;

  const outputAmount =
    typeof recipe["output_amount"] === "number"
      ? recipe["output_amount"]
      : typeof recipe["count"] === "number"
        ? recipe["count"]
        : undefined;

  return {
    ingredients,
    ...(craftingType ? { craftingType } : {}),
    ...(outputAmount !== undefined ? { outputAmount } : {}),
  };
}

export async function getItems(): Promise<WikiItem[]> {
  try {
    if (itemsCache && Date.now() - itemsCache.at < 30 * 60_000) {
      return itemsCache.items;
    }

    const data = await getJson<ItemsResponse>(`${API}/resources/skyblock/items`);

    if (!data || !Array.isArray(data.items)) {
      return [];
    }

    const items: WikiItem[] = data.items.map((item) => {
      const extra = ITEM_EXTRAS[item.id];

      const description =
        normalizeDescription(typeof item.description === "string" ? item.description : item.lore) ??
        (Array.isArray(extra?.lore) && extra.lore.length
          ? normalizeDescription(extra.lore)
          : undefined);

      const stats =
        item.stats && typeof item.stats === "object" && Object.keys(item.stats).length > 0
          ? (item.stats as Record<string, number>)
          : extra?.stats;

      const abilities =
        normalizeAbilities(item.abilities) ??
        (extra?.abilities?.length
          ? extra.abilities.map((ability) => ({
              name: ability.name,
              description: ability.desc,
              ...(ability.manaCost != null
                ? {
                    manaCost: ability.manaCost,
                  }
                : {}),
              ...(ability.cooldown != null
                ? {
                    cooldown: ability.cooldown,
                  }
                : {}),
            }))
          : undefined);

      const requirements =
        normalizeRequirements(item.requirements) ??
        (extra?.requirements?.length ? extra.requirements : undefined);

      const recipe =
        normalizeRecipe(item.recipe) ??
        normalizeRecipe(
          (generatedRecipes as Record<string, unknown>)[item.id] !== undefined
            ? {
                ingredients: (generatedRecipes as Record<string, { id: string; amount: number }[]>)[
                  item.id
                ],
              }
            : undefined,
        );

      return {
        id: item.id,
        name: (item.name ?? titleCase(item.id)).replace(/§./g, "").trim(),

        ...(item.material !== undefined ? { material: item.material } : {}),
        rarity: item.tier ?? "COMMON",
        category: item.category ? titleCase(item.category) : "Misc",

        npcSell: typeof item.npc_sell_price === "number" ? item.npc_sell_price : null,

        ...(description !== undefined ? { description } : {}),

        ...(Array.isArray(extra?.lore) && extra.lore.length
          ? {
              lore: extra.lore.map((line) =>
                line.replace(/§./g, "").replace(/[\uDC00-\uDFFF\uE000-\uF8FF]/g, ""),
              ),
            }
          : {}),

        ...(stats ? { stats } : {}),

        ...(abilities ? { abilities } : {}),

        ...(requirements ? { requirements } : {}),

        ...(recipe ? { recipe } : {}),

        ...(extra?.wikiUrl ? { wikiUrl: extra.wikiUrl } : {}),
      };
    });

    itemsCache = {
      at: Date.now(),
      items,
    };

    return items;
  } catch (err) {
    console.error("Error inside getItems:", err);
    return [];
  }
}

async function nameLookup(): Promise<Map<string, string>> {
  try {
    const items = await getItems();

    return new Map(items.map((item) => [item.id, item.name]));
  } catch {
    return new Map();
  }
}

// ============================================================================
// BAZAAR
// ============================================================================

type BazaarResponse = {
  lastUpdated: number;

  products: Record<
    string,
    {
      quick_status: {
        productId: string;
        buyPrice: number;
        sellPrice: number;
        buyVolume: number;
        sellVolume: number;
        buyMovingWeek: number;
        sellMovingWeek: number;
        buyOrders: number;
        sellOrders: number;
      };
    }
  >;
};

export async function getBazaar(): Promise<{
  lastUpdated: number;
  products: BazaarProduct[];
}> {
  try {
    const [data, names] = await Promise.all([
      getJson<BazaarResponse>(`${API}/skyblock/bazaar`),
      nameLookup(),
    ]);

    if (!data || !data.products) {
      return {
        lastUpdated: Date.now(),
        products: [],
      };
    }

    const products: BazaarProduct[] = [];

    for (const [id, entry] of Object.entries(data.products)) {
      const q = entry.quick_status;

      if (
        !q ||
        !Number.isFinite(q.buyPrice) ||
        !Number.isFinite(q.sellPrice) ||
        q.buyPrice <= 0 ||
        q.sellPrice <= 0
      ) {
        continue;
      }

      const gross = q.buyPrice - q.sellPrice;

      const spread = gross - q.buyPrice * 0.0125;

      if (spread <= 0) {
        continue;
      }

      const flipsPerHour = Math.min(q.buyMovingWeek, q.sellMovingWeek) / 168;

      const liquidity = Math.min(100, Math.round(Math.log10(Math.max(1, flipsPerHour)) * 25));

      const margin = (spread / q.sellPrice) * 100;

      products.push({
        id,

        name: names.get(id) ?? titleCase(id.replace(/^ENCHANTED_/, "Enchanted ")),

        buyPrice: q.buyPrice,
        sellPrice: q.sellPrice,
        spread,
        margin,

        buyVolume: q.buyVolume,
        sellVolume: q.sellVolume,

        buyMovingWeek: q.buyMovingWeek,

        sellMovingWeek: q.sellMovingWeek,

        profitPerHour: spread * flipsPerHour,

        liquidity,

        health: Math.min(100, Math.round(liquidity * 0.6 + Math.min(margin, 60) * 0.7)),
      });
    }

    products.sort((a, b) => b.profitPerHour - a.profitPerHour);

    return {
      lastUpdated: data.lastUpdated || Date.now(),
      products,
    };
  } catch (err) {
    console.error("Error in getBazaar:", err);

    return {
      lastUpdated: Date.now(),
      products: [],
    };
  }
}

// ============================================================================
// AUCTIONS
// ============================================================================

type AuctionsResponse = {
  page: number;
  totalPages: number;
  totalAuctions: number;
  lastUpdated: number;

  auctions: Array<{
    uuid: string;

    item_bytes?:
      | string
      | {
          type?: number;
          data?: string;
        };

    item_id?: string;
    item_name: string;
    tier: string;
    bin: boolean;
    starting_bid: number;
    highest_bid_amount: number;
    end: number;
    bids: unknown[];
    category: string;
    item_lore: string;
  }>;
};

type AuctionItemIdentity = Pick<AuctionEntry, "id" | "texture">;

type AuctionCandidate = {
  entry: AuctionEntry;
  uuid: string;
  itemBytes: AuctionsResponse["auctions"][number]["item_bytes"];
};

const auctionItemCache = new Map<
  string,
  {
    at: number;
    identity: AuctionItemIdentity;
  }
>();

const AUCTION_ITEM_CACHE_TTL_MS = 15 * 60_000;

const AUCTION_ICON_LIMIT = 240;
const AUCTION_ITEM_DECODE_CONCURRENCY = 8;

function itemBytesData(
  itemBytes: AuctionsResponse["auctions"][number]["item_bytes"],
): string | undefined {
  if (typeof itemBytes === "string") {
    return itemBytes;
  }

  if (typeof itemBytes?.data === "string") {
    return itemBytes.data;
  }

  return undefined;
}

function nbtObject(value: NbtValue | undefined): Record<string, NbtValue> | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return null;
  }

  const object = value as Record<string, NbtValue>;

  const wrapped = object["value"];

  if (wrapped && typeof wrapped === "object" && !Array.isArray(wrapped)) {
    return wrapped as Record<string, NbtValue>;
  }

  return object;
}

function nbtArray(value: NbtValue | undefined): NbtValue[] {
  if (Array.isArray(value)) {
    return value;
  }

  const object = nbtObject(value);
  const wrapped = object?.["value"];

  return Array.isArray(wrapped) ? wrapped : [];
}

function textureFromTag(tag: Record<string, NbtValue>): string | undefined {
  const skullOwner = nbtObject(tag["SkullOwner"]);

  const properties = nbtObject(skullOwner?.["Properties"]);

  const textures = nbtArray(properties?.["textures"]);

  const firstTexture = nbtObject(textures[0]);

  const value = firstTexture?.["Value"] ?? firstTexture?.["value"];

  if (typeof value !== "string" || !value) {
    return undefined;
  }

  try {
    const decoded = JSON.parse(Buffer.from(value, "base64").toString("utf8")) as {
      textures?: {
        SKIN?: {
          url?: string;
        };
      };
    };

    return decoded.textures?.SKIN?.url?.replace(/^http:/, "https:");
  } catch {
    return value.startsWith("http")
      ? value.replace(/^http:/, "https:")
      : `https://textures.minecraft.net/texture/${value}`;
  }
}

async function extractAuctionItemIdentity(
  itemBytes: AuctionsResponse["auctions"][number]["item_bytes"],
): Promise<AuctionItemIdentity> {
  const data = itemBytesData(itemBytes);

  if (!data) {
    return {};
  }

  try {
    const root = await decodeNbt(data);

    const itemStack = nbtObject(nbtArray(root["i"])[0]);

    const tag = nbtObject(itemStack?.["tag"]);

    const extra = nbtObject(tag?.["ExtraAttributes"]);

    const id = extra?.["id"];

    const texture = tag ? textureFromTag(tag) : undefined;

    return {
      ...(typeof id === "string" && id ? { id } : {}),

      ...(texture ? { texture } : {}),
    };
  } catch {
    return {};
  }
}

function pruneAuctionItemCache(now: number) {
  for (const [uuid, cached] of auctionItemCache) {
    if (now - cached.at > AUCTION_ITEM_CACHE_TTL_MS) {
      auctionItemCache.delete(uuid);
    }
  }
}

async function auctionItemIdentity(
  uuid: string,
  itemBytes: AuctionsResponse["auctions"][number]["item_bytes"],
): Promise<AuctionItemIdentity> {
  const now = Date.now();

  const cached = auctionItemCache.get(uuid);

  if (cached && now - cached.at <= AUCTION_ITEM_CACHE_TTL_MS) {
    return cached.identity;
  }

  const identity = await extractAuctionItemIdentity(itemBytes);

  auctionItemCache.set(uuid, {
    at: now,
    identity,
  });

  return identity;
}

async function hydrateAuctionEntries(candidates: AuctionCandidate[]): Promise<AuctionEntry[]> {
  const entries = candidates.map(({ entry }) => entry);

  let next = 0;

  const worker = async () => {
    for (;;) {
      const index = next++;
      const candidate = candidates[index];

      if (!candidate) {
        return;
      }

      const identity = await auctionItemIdentity(candidate.uuid, candidate.itemBytes);

      const id = candidate.entry.id ?? identity.id;

      entries[index] = {
        ...candidate.entry,

        ...(id ? { id } : {}),

        ...(identity.texture
          ? {
              texture: identity.texture,
            }
          : {}),
      };
    }
  };

  await Promise.all(
    Array.from(
      {
        length: Math.min(AUCTION_ITEM_DECODE_CONCURRENCY, candidates.length),
      },
      worker,
    ),
  );

  return entries;
}

// Shared auction scan cache: one 24-page scan serves every visitor for the
// TTL window instead of re-fetching Hypixel per request.
const auctionScanCache = new Map<
  number,
  { at: number; data: Awaited<ReturnType<typeof getAuctions>> }
>();
const AUCTION_CACHE_TTL = 3 * 60_000;

export async function getAuctions(pages = 6): Promise<{
  lastUpdated: number;
  totalAuctions: number;
  totalPages: number;
  binCount: number;
  auctionCount: number;
  uniqueItems: number;
  averageBin: number;
  entries: AuctionEntry[];
}> {
  const cached = auctionScanCache.get(pages);
  if (cached && Date.now() - cached.at < AUCTION_CACHE_TTL) {
    return cached.data;
  }

  const fallback = {
    lastUpdated: Date.now(),
    totalAuctions: 0,
    totalPages: 0,
    binCount: 0,
    auctionCount: 0,
    uniqueItems: 0,
    averageBin: 0,
    entries: [] as AuctionEntry[],
  };

  try {
    const first = await getJson<AuctionsResponse>(`${API}/skyblock/auctions?page=0`);

    if (!first || !Array.isArray(first.auctions)) {
      return fallback;
    }

    const wanted = Math.min(Math.max(1, pages), first.totalPages || 1);

    const rest = await Promise.all(
      Array.from(
        {
          length: Math.max(0, wanted - 1),
        },
        (_, i) =>
          getJson<AuctionsResponse>(`${API}/skyblock/auctions?page=${i + 1}`).catch(() => null),
      ),
    );

    const all = [
      first,
      ...rest.filter(
        (value): value is AuctionsResponse => value !== null && Array.isArray(value.auctions),
      ),
    ];

    const raw = all.flatMap((page) => page.auctions);

    const lowestBin = new Map<string, number>();

    let binCount = 0;
    let binTotal = 0;

    for (const auction of raw) {
      if (!auction.bin) {
        continue;
      }

      binCount += 1;
      binTotal += auction.starting_bid;

      const key = `${auction.item_name}|${auction.tier}`;

      const previous = lowestBin.get(key);

      if (previous === undefined || auction.starting_bid < previous) {
        lowestBin.set(key, auction.starting_bid);
      }
    }

    const now = Date.now();

    pruneAuctionItemCache(now);

    const candidates: AuctionCandidate[] = raw.map((auction) => {
      const key = `${auction.item_name}|${auction.tier}`;

      const price = auction.bin
        ? auction.starting_bid
        : Math.max(auction.highest_bid_amount, auction.starting_bid);

      const lb = lowestBin.get(key) ?? null;

      return {
        uuid: auction.uuid,

        itemBytes: auction.item_bytes,

        entry: {
          uuid: auction.uuid,

          ...(auction.item_id
            ? {
                id: auction.item_id,
              }
            : {}),

          name: auction.item_name,

          rarity: auction.tier,

          bin: auction.bin,

          price,

          topBid: auction.bin ? null : Math.max(auction.highest_bid_amount, 0) || null,

          lowestBin: lb,

          profit: lb !== null ? lb - price : 0,

          endsInMs: auction.end - now,

          bids: Array.isArray(auction.bids) ? auction.bids.length : 0,

          category: auction.category ? titleCase(auction.category) : "Misc",
        },
      };
    });

    const entries = await hydrateAuctionEntries(
      candidates
        .sort((a, b) => b.entry.profit - a.entry.profit || b.entry.price - a.entry.price)
        .slice(0, AUCTION_ICON_LIMIT),
    );

    const result = {
      lastUpdated: first.lastUpdated || now,

      totalAuctions: first.totalAuctions || raw.length,

      totalPages: first.totalPages || 1,

      binCount,

      auctionCount: raw.length - binCount,

      uniqueItems: lowestBin.size,

      averageBin: binCount ? binTotal / binCount : 0,

      entries,
    };

    // Only cache successful, non-empty scans so a bad response never sticks.
    if (entries.length > 0) {
      auctionScanCache.set(pages, { at: Date.now(), data: result });
    }

    return result;
  } catch (err) {
    console.error("Error in getAuctions:", err);

    return fallback;
  }
}

// ============================================================================
// WIKI MARKET DATA
// ============================================================================

type WikiAuctionStats = {
  lowestBin: number | null;
  averageBin: number | null;
  medianBin: number | null;
  listings: number;
};

function calculateAuctionStats(auctions: AuctionEntry[]): Map<string, WikiAuctionStats> {
  const grouped = new Map<string, number[]>();

  for (const auction of auctions) {
    if (!auction.bin) {
      continue;
    }

    if (!auction.id) {
      continue;
    }

    const prices = grouped.get(auction.id) ?? [];

    prices.push(auction.price);

    grouped.set(auction.id, prices);
  }

  const result = new Map<string, WikiAuctionStats>();

  for (const [id, prices] of grouped) {
    if (!prices.length) {
      continue;
    }

    prices.sort((a, b) => a - b);

    const total = prices.reduce((sum, value) => sum + value, 0);

    const middle = Math.floor(prices.length / 2);

    const median =
      prices.length % 2 === 0
        ? ((prices[middle - 1] ?? 0) + (prices[middle] ?? 0)) / 2
        : (prices[middle] ?? 0);

    result.set(id, {
      lowestBin: prices[0] ?? null,

      averageBin: prices.length ? total / prices.length : null,

      medianBin: median,

      listings: prices.length,
    });
  }

  return result;
}

export async function getWikiItems(): Promise<WikiItem[]> {
  const [items, bazaarResponse, auctionResponse] = await Promise.all([
    getItems(),

    getJson<BazaarResponse>(`${API}/skyblock/bazaar`),

    getAuctions(6),
  ]);

  const bazaarMap = new Map<string, WikiMarketData["bazaar"]>();

  if (bazaarResponse?.products) {
    for (const [id, entry] of Object.entries(bazaarResponse.products)) {
      const q = entry.quick_status;

      if (!q) {
        continue;
      }

      bazaarMap.set(id, {
        buyPrice: q.buyPrice,
        sellPrice: q.sellPrice,
        buyVolume: q.buyVolume,
        sellVolume: q.sellVolume,
        buyMovingWeek: q.buyMovingWeek,
        sellMovingWeek: q.sellMovingWeek,
        buyOrders: q.buyOrders,
        sellOrders: q.sellOrders,
      });
    }
  }

  const auctionMap = calculateAuctionStats(auctionResponse.entries);

  return items.map((item) => {
    const bazaar = bazaarMap.get(item.id);

    const auctionHouse = auctionMap.get(item.id);

    const demand = bazaar
      ? Math.min(
          100,
          Math.round(Math.log10(Math.max(1, bazaar.buyMovingWeek + bazaar.sellMovingWeek)) * 20),
        )
      : null;

    const volume = bazaar ? bazaar.buyMovingWeek + bazaar.sellMovingWeek : null;

    return {
      ...item,

      ...(bazaar
        ? {
            bazaar,
          }
        : {}),

      ...(auctionHouse
        ? {
            auctionHouse,
          }
        : {}),

      // Hypixel's public item API does not provide
      // a true historical price series. Keep this
      // null rather than inventing historical data.
      historicalPrice: null,

      ...(demand !== null ? { demand } : {}),

      ...(volume !== null ? { volume } : {}),
    };
  });
}

// ============================================================================
// ITEM LOOKUP
// ============================================================================

export async function getWikiItem(itemId: string): Promise<WikiItem | null> {
  const normalized = itemId.trim().toUpperCase();

  if (!normalized) {
    return null;
  }

  const items = await getWikiItems();

  return items.find((item) => item.id.toUpperCase() === normalized) ?? null;
}

/**
 * Full encyclopedia payload for one item: the merged item record plus
 * NEU extras (crafting grid, canonical wiki URL, craft text) and a
 * reverse "used to craft" index built from all known recipes.
 */
export async function getItemEncyclopedia(itemId: string): Promise<{
  item: WikiItem | null;
  extra: ItemExtra | null;
  usedIn: Array<{ id: string; name: string; amount: number }>;
}> {
  const normalized = itemId.trim().toUpperCase();
  if (!normalized) {
    return { item: null, extra: null, usedIn: [] };
  }

  const [items, recipes] = await Promise.all([getWikiItems(), getRecipeIndex()]);

  const item = items.find((entry) => entry.id.toUpperCase() === normalized) ?? null;

  const extra = ITEM_EXTRAS[normalized] ?? null;

  const names = new Map(items.map((entry) => [entry.id, entry.name]));

  const usedIn = (recipes.get(normalized) ?? [])
    .map(({ id, amount }) => ({
      id,
      amount,
      name: names.get(id) ?? titleCase(id),
    }))
    .sort((a, b) => b.amount - a.amount || a.name.localeCompare(b.name));

  return { item, extra, usedIn };
}

/** Internal ID -> list of recipes that consume it (reverse crafting index). */
async function getRecipeIndex(): Promise<Map<string, Array<{ id: string; amount: number }>>> {
  const items = await getItems();
  const index = new Map<string, Array<{ id: string; amount: number }>>();

  for (const item of items) {
    if (!item.recipe) continue;
    for (const ingredient of item.recipe.ingredients) {
      const list = index.get(ingredient.id.toUpperCase()) ?? [];
      list.push({ id: item.id, amount: ingredient.amount });
      index.set(ingredient.id.toUpperCase(), list);
    }
  }

  return index;
}

// ============================================================================
// PLAYER PROFILE + COLLECTIONS
// ============================================================================

const RARITY_WORDS = [
  "DIVINE",
  "VERY SPECIAL",
  "SPECIAL",
  "MYTHIC",
  "LEGENDARY",
  "EPIC",
  "RARE",
  "UNCOMMON",
  "COMMON",
];

function stripColors(value: string): string {
  return value.replace(/§./g, "");
}

function rarityFromLore(lore: string[]): string {
  for (let i = lore.length - 1; i >= 0; i--) {
    const line = stripColors(lore[i] ?? "").toUpperCase();

    const hit = RARITY_WORDS.find((rarity) => line.includes(rarity));

    if (hit) {
      return hit.replace(" ", "_");
    }
  }

  return "COMMON";
}

function getCollectionCategory(itemId: string): string {
  const id = itemId.toUpperCase();

  // Mining
  if (
    id.includes("GEMSTONE") ||
    id.includes("MINING") ||
    [
      "COBBLESTONE",
      "COAL",
      "IRON_INGOT",
      "GOLD_INGOT",
      "DIAMOND",
      "EMERALD",
      "REDSTONE",
      "QUARTZ",
      "OBSIDIAN",
      "GLOWSTONE",
      "GRAVEL",
      "ICE",
      "NETHERRACK",
      "SAND",
      "END_STONE",
      "MITHRIL_ORE",
      "TITANIUM_ORE",
      "HARD_STONE",
      "SULPHUR",
    ].some((key) => id.includes(key))
  ) {
    return "Mining";
  }

  // Farming
  if (
    id.includes("FARMING") ||
    [
      "WHEAT",
      "CARROT",
      "POTATO",
      "PUMPKIN",
      "MELON",
      "SEEDS",
      "MUSHROOM",
      "COCOA",
      "CACTUS",
      "SUGAR_CANE",
      "NETHER_STALK",
      "FEATHER",
      "LEATHER",
      "PORK",
      "RAW_CHICKEN",
      "MUTTON",
      "RABBIT",
    ].some((key) => id.includes(key))
  ) {
    return "Farming";
  }

  // Combat
  if (
    id.includes("COMBAT") ||
    [
      "ROTTEN_FLESH",
      "BONE",
      "STRING",
      "SPIDER_EYE",
      "GUNPOWDER",
      "ENDER_PEARL",
      "BLAZE_ROD",
      "SLIME_BALL",
      "MAGMA_CREAM",
      "GHAST_TEAR",
      "ENDERMITE",
    ].some((key) => id.includes(key))
  ) {
    return "Combat";
  }

  // Foraging
  if (
    id.includes("LOG") ||
    id.includes("WOOD") ||
    ["JUNGLE", "ACACIA", "DARK_OAK", "BIRCH", "SPRUCE", "OAK"].some((key) => id.includes(key))
  ) {
    return "Foraging";
  }

  // Fishing
  if (
    id.includes("FISH") ||
    [
      "RAW_FISH",
      "PRISMARINE_SHARD",
      "PRISMARINE_CRYSTALS",
      "CLAY_BALL",
      "WATER_LILY",
      "INK_SACK",
      "SPONGE",
    ].some((key) => id.includes(key))
  ) {
    return "Fishing";
  }

  if (id.includes("RIFT")) {
    return "Rift";
  }

  return "Misc";
}

// ============================================================================
// CONTAINERS
// ============================================================================

async function parseContainer(
  base64: string | undefined,
  id: string,
  label: string,
): Promise<InventoryContainer | null> {
  if (!base64) {
    return null;
  }

  try {
    const root = await decodeNbt(base64);

    const list = nbtArray(root["i"]);

    const items: InventoryItem[] = [];

    list.forEach((entry, index) => {
      const it = nbtObject(entry);

      if (!it) {
        return;
      }

      const tag = nbtObject(it["tag"]) ?? {};

      const display = nbtObject(tag["display"]) ?? {};

      const extra = nbtObject(tag["ExtraAttributes"]) ?? {};

      // Empty slots have no item id — skip them entirely.
      const itemId = extra["id"];
      if (typeof itemId !== "string" || !itemId) {
        return;
      }

      const lore = nbtArray(display["Lore"]).map((line) => stripColors(String(line)));

      const rawName = display["Name"] ?? extra["id"] ?? "Unknown Item";

      const name = stripColors(String(rawName));

      const texture = textureFromTag(tag);
      const rawCount = it["Count"];

      const count = typeof rawCount === "number" ? rawCount : Number(rawCount ?? 1);

      // NBT ExtraAttributes: enchantments, reforge, gems, stars, HPBs.
      const enchantmentsRaw = nbtObject(extra["enchantments"]);
      const enchantments: Record<string, number> = {};
      for (const [ench, level] of Object.entries(enchantmentsRaw ?? {})) {
        const num = Number(level);
        if (Number.isFinite(num) && num > 0) enchantments[ench] = num;
      }

      const reforgeRaw = extra["modifier"];
      const gemsRaw = nbtObject(extra["gems"]);
      const gems: Record<string, string> = {};
      for (const [slot, gem] of Object.entries(gemsRaw ?? {})) {
        if (typeof gem === "string" && gem && !/_gem$/.test(slot)) {
          gems[slot] = gem;
        }
      }

      const starsRaw = extra["dungeon_item_level"] ?? extra["upgrade_level"];
      const hpbRaw = extra["hot_potato_count"];

      const scrollsRaw = nbtArray(extra["ability_scroll"]);

      const attributesRaw = nbtObject(extra["attributes"]);
      const attributes: Record<string, number> = {};
      for (const [attrKey, attrLvl] of Object.entries(attributesRaw ?? {})) {
        const num = Number(attrLvl);
        if (Number.isFinite(num) && num > 0) attributes[attrKey] = num;
      }

      const artOfWarRaw = extra["art_of_war_count"];
      const woodSingularityRaw = extra["wood_singularity_count"];

      items.push({
        slot: index,

        name,

        id: itemId,

        ...(texture ? { texture } : {}),

        rarity: rarityFromLore(lore),

        count: Number.isFinite(count) ? count : 1,

        lore,

        ...(Object.keys(enchantments).length > 0 ? { enchantments } : {}),

        ...(typeof reforgeRaw === "string" && reforgeRaw
          ? { reforge: titleCase(reforgeRaw.replace(/_/g, " ")) }
          : {}),

        ...(typeof starsRaw === "number" && starsRaw > 0 ? { stars: starsRaw } : {}),

        ...(typeof hpbRaw === "number" && hpbRaw > 0 ? { hotPotatoBooks: hpbRaw } : {}),

        ...(Object.keys(gems).length > 0 ? { gems } : {}),

        ...(scrollsRaw.length > 0
          ? {
              abilityScrolls: scrollsRaw
                .map((s) => titleCase(String(s).replace(/_/g, " ")))
                .slice(0, 3),
            }
          : {}),

        ...(Object.keys(attributes).length > 0 ? { attributes } : {}),

        ...(typeof artOfWarRaw === "number" && artOfWarRaw > 0 ? { artOfWar: artOfWarRaw } : {}),

        ...(typeof woodSingularityRaw === "number" && woodSingularityRaw > 0
          ? { woodSingularity: woodSingularityRaw }
          : {}),
      });
    });

    return {
      id,
      label,

      slots: Math.max(list.length, items.length),

      items,
    };
  } catch {
    return {
      id,
      label,
      slots: 0,
      items: [],
      locked: true,
    };
  }
}

// ============================================================================
// PROFILES
// ============================================================================

type ProfilesResponse = {
  profiles: Array<{
    profile_id: string;
    cute_name: string;
    game_mode?: string;
    selected: boolean;

    banking?: {
      balance?: number;
    };

    community_upgrades?: {
      upgrades?: Array<{ upgrade?: string; tier?: number }>;
    };

    members: Record<string, Record<string, unknown>>;
  }> | null;
};

export async function getPlayerData(
  apiKey: string,
  username: string,
  profileId?: string,
): Promise<PlayerDataValidated | null> {
  const userKeyProvided = Boolean(apiKey?.trim());
  try {
    if (!username) {
      return null;
    }

    const resolved = await resolveUuid(username);

    if (!resolved) {
      return null;
    }

    const { uuid, name } = resolved;

    // Profiles change slowly — serve a short-TTL cache so one operator key
    // can serve many visitors and repeat views are instant.
    const cacheKey = `${uuid}:${profileId ?? ""}`;
    const cached = profileCache.get(cacheKey);
    if (!userKeyProvided && cached && Date.now() - cached.at < PROFILE_CACHE_TTL) {
      return cached.data as PlayerDataValidated;
    }

    const data = await getKeyedJson<ProfilesResponse>(
      `${API}/skyblock/profiles?uuid=${uuid}`,
      apiKey,
    );

    const list = data?.profiles ?? [];

    if (!list.length) {
      return null;
    }

    const chosen =
      list.find((profile) => profile.profile_id === profileId) ??
      list.find((profile) => profile.selected) ??
      list[0]!;

    const member = chosen.members[uuid] ?? {};

    const summaries: ProfileSummary[] = list.map((profile) => ({
      profileId: profile.profile_id,

      cuteName: profile.cute_name,

      gameMode: profile.game_mode ? titleCase(profile.game_mode) : "Classic",

      members: Object.keys(profile.members).length,

      selected: profile.profile_id === chosen.profile_id,
    }));

    const experience =
      (
        member["player_data"] as
          | {
              experience?: Record<string, number>;
            }
          | undefined
      )?.experience ?? {};

    const skills = SKILL_META.map((meta) =>
      computeSkill(meta.key as SkillKey, Number(experience[`SKILL_${meta.key}`] ?? 0)),
    );

    const rated = skills.filter((skill) => skill.key !== "RUNECRAFTING" && skill.key !== "SOCIAL");

    const skillAverage = rated.reduce((sum, skill) => sum + skill.level, 0) / (rated.length || 1);

    const inv = (member["inventory"] ?? {}) as Record<
      string,
      | {
          data?: string;
          talisman_bag?: { data?: string };
          quiver?: { data?: string };
          potion_bag?: { data?: string };
          fishing_bag?: { data?: string };
        }
      | undefined
    >;

    const containerDefs: Array<[string | undefined, string, string]> = [
      [inv?.["inv_contents"]?.["data"], "inventory", "Inventory"],

      [inv?.["ender_chest_contents"]?.["data"], "ender-chest", "Ender Chest"],

      [inv?.["inv_armor"]?.["data"], "armor", "Armor"],

      [inv?.["equipment_contents"]?.["data"], "equipment", "Equipment"],

      [inv?.["wardrobe_contents"]?.["data"], "wardrobe", "Wardrobe"],

      [inv?.["bag_contents"]?.["talisman_bag"]?.["data"], "accessory-bag", "Accessory Bag"],

      [inv?.["bag_contents"]?.["quiver"]?.["data"], "quiver", "Quiver"],

      [inv?.["bag_contents"]?.["potion_bag"]?.["data"], "potion-bag", "Potion Bag"],

      [inv?.["bag_contents"]?.["fishing_bag"]?.["data"], "fishing-bag", "Fishing Bag"],

      [inv?.["personal_vault_contents"]?.["data"], "vault", "Personal Vault"],
    ];

    const backpacks = (inv?.["backpack_contents"] ?? {}) as Record<
      string,
      {
        data?: string;
      }
    >;

    for (const [key, value] of Object.entries(backpacks)) {
      containerDefs.push([value?.data, `backpack-${key}`, `Backpack ${Number(key) + 1}`]);
    }

    const containers = (
      await Promise.all(
        containerDefs.map(([encoded, id, label]) => parseContainer(encoded, id, label)),
      )
    ).filter(
      (container): container is InventoryContainer =>
        !!container && (container.items.length > 0 || !!container.locked),
    );

    const collectionRaw = (member["collection"] ?? {}) as Record<string, number>;

    const names = await nameLookup();

    const collections = Object.entries(collectionRaw)
      .map(([id, amount]) => ({
        id,

        name: names.get(id) ?? titleCase(id),

        category: getCollectionCategory(id),

        amount: Number(amount) || 0,
      }))
      .sort((a, b) => b.amount - a.amount);

    const currencies = member["currencies"] as
      | {
          coin_purse?: number;
        }
      | undefined;

    const fairySoul = member["fairy_soul"] as
      | {
          total_collected?: number;
        }
      | undefined;

    // Dungeons: catacombs level/XP, secrets and per-floor completions.
    const dungeonsRaw = member["dungeons"] as
      | {
          dungeon_types?: {
            catacombs?: {
              experience?: number;
              tier_completions?: Record<string, number>;
              best_score?: Record<string, number>;
              highest_tier_completions?: Record<string, number>;
            };
            master_catacombs?: {
              experience?: number;
              tier_completions?: Record<string, number>;
              best_score?: Record<string, number>;
            };
          };
          secrets?: number;
          player_classes?: Record<string, { experience?: number }>;
          selected_dungeon_class?: string;
          dungeon_xp?: number;
          milestone_completions?: number;
        }
      | undefined;

    const dungeonsRoot = member["dungeons"] as
      | {
          dungeon_types?: {
            catacombs?: {
              experience?: number;
              tier_completions?: Record<string, number>;
              best_score?: Record<string, number>;
            };
            master_catacombs?: {
              experience?: number;
              tier_completions?: Record<string, number>;
              best_score?: Record<string, number>;
            };
          };
          secrets?: number;
          player_classes?: Record<string, { experience?: number }>;
          selected_dungeon_class?: string;
          milestone_completions?: number;
        }
      | undefined;

    const catacombs = dungeonsRaw?.dungeon_types?.catacombs;
    const masterCatacombs = dungeonsRoot?.dungeon_types?.master_catacombs;

    const floorEntries = (
      completions: Record<string, number> | undefined,
      best: Record<string, number> | undefined,
      prefix: string,
    ) =>
      Object.entries(completions ?? {})
        .filter(([tier]) => tier !== "total" && tier !== "master_mode")
        .map(([tier, completions]) => ({
          name: `${prefix}${tier}`,
          completions: Number(completions) || 0,
          bestScore: Number(best?.[tier] ?? 0),
        }))
        .sort((a, b) => a.name.localeCompare(b.name));

    const dungeonClasses = Object.entries(dungeonsRoot?.player_classes ?? {}).map(
      ([key, data]) => ({
        name: titleCase(key),
        level: computeSkill("COMBAT", Number(data?.experience ?? 0)).level,
        selected: dungeonsRoot?.selected_dungeon_class === key,
      }),
    );

    const dungeons = catacombs
      ? {
          catacombsLevel: computeSkill("COMBAT", Number(catacombs.experience ?? 0)).level,
          catacombsXp: Number(catacombs.experience ?? 0),
          secretsFound: Number(dungeonsRoot?.secrets ?? 0),
          floors: floorEntries(catacombs.tier_completions, catacombs.best_score, "Floor "),
          ...(masterCatacombs
            ? {
                masterMode: floorEntries(
                  masterCatacombs.tier_completions,
                  masterCatacombs.best_score,
                  "M",
                ),
                masterModeLevel: computeSkill("COMBAT", Number(masterCatacombs.experience ?? 0))
                  .level,
                masterModeXp: Number(masterCatacombs.experience ?? 0),
              }
            : {}),
          ...(dungeonClasses.length ? { classes: dungeonClasses } : {}),
          ...(Number(dungeonsRoot?.milestone_completions ?? 0) > 0
            ? { milestones: Number(dungeonsRoot?.milestone_completions) }
            : {}),
        }
      : undefined;

    // Slayers: kills per boss per tier + XP + claimed levels.
    const slayerRaw = member["slayer_bosses"] as
      | Record<
          string,
          {
            claimed_levels?: Record<string, unknown>;
            boss_kills_tier?: Record<string, number>;
            xp?: number;
            claimed_xp?: Record<string, number>;
          }
        >
      | undefined;

    const SLAYER_NAMES: Record<string, string> = {
      zombie: "Revenant Horror",
      spider: "Tarantula Broodfather",
      wolf: "Sven Packmaster",
      enderman: "Voidgloom Seraph",
      blaze: "Inferno Demonlord",
      vampire: "Riftstalker Bloodfiend",
    };

    const slayers = Object.entries(slayerRaw ?? {}).flatMap(([key, data]) =>
      Object.entries(data.boss_kills_tier ?? {}).map(([tier, kills]) => ({
        name: SLAYER_NAMES[key] ?? titleCase(key),
        tier: Number(tier),
        kills: Number(kills) || 0,
        ...(Number(data.claimed_xp?.[tier] ?? 0) > 0
          ? { xp: Number(data.claimed_xp?.[tier]) }
          : {}),
      })),
    );

    // Pets: name, rarity, level, XP + extras (active/held/skin/candy).
    const petsRaw = member["pets_data"] as
      | {
          pets?: Array<{
            type?: string;
            name?: string;
            tier?: string;
            experience?: number;
            heldItem?: string | null;
            skin?: string | null;
            candyUsed?: number;
            uuid?: string;
          }>;
          current?: string | null;
        }
      | undefined;

    const pets = (petsRaw?.pets ?? [])
      .map((pet) => ({
        name: titleCase(String(pet.name ?? pet.type ?? "Pet")),
        rarity: String(pet.tier ?? "COMMON"),
        level: computePetLevel(Number(pet.experience ?? 0)),
        xp: Number(pet.experience ?? 0),
        ...(petsRaw?.current && pet.uuid && petsRaw.current === pet.uuid ? { active: true } : {}),
        ...(pet.heldItem ? { heldItem: titleCase(String(pet.heldItem).replace(/_/g, " ")) } : {}),
        ...(pet.skin ? { skin: String(pet.skin) } : {}),
        ...(Number(pet.candyUsed ?? 0) > 0 ? { candyUsed: Number(pet.candyUsed) } : {}),
      }))
      .sort((a, b) => b.level - a.level || b.xp - a.xp);

    // Heart of the Mountain (mining core).
    const miningCore = member["mining_core"] as
      | {
          nodes?: Record<string, number | { level?: number }>;
          powders?: Record<string, number>;
          experience?: number;
          tiers_area?: Record<string, number>;
          selected_pickaxe_uid?: string;
        }
      | undefined;

    // HOTM has its own XP curve (roughly: tier N requires ~640 * N^2.6 XP).
    function hotmTierFromXp(xp: number): number {
      if (xp <= 0) return 0;
      let tier = 0;
      for (let t = 1; t <= 10; t++) {
        if (xp >= 640 * Math.pow(t, 2.6)) tier = t;
        else break;
      }
      return tier;
    }

    let hotm: import("./skyblock").HotmStats | undefined;
    if (
      miningCore &&
      (Number(miningCore.experience ?? 0) > 0 || Object.keys(miningCore.nodes ?? {}).length > 0)
    ) {
      const nodes: Record<string, number> = {};
      let hotmLevelFromNodes = 0;
      for (const [key, value] of Object.entries(miningCore.nodes ?? {})) {
        if (key.endsWith("_level")) {
          const nodeKey = key.replace(/_level$/, "").replace(/^node_\d+_/, "");
          const level =
            typeof value === "number"
              ? value
              : Number((value as { level?: number } | undefined)?.level ?? 0);
          if (level > 0) nodes[nodeKey] = level;
          // HOTM tier is stored directly as the hotm node level.
          if (/^hotm$/.test(nodeKey)) hotmLevelFromNodes = level;
        }
      }
      const xp = Number(miningCore.experience ?? 0);
      const tier = hotmLevelFromNodes > 0 ? hotmLevelFromNodes : hotmTierFromXp(xp);
      hotm = {
        tier,
        xp,
        powders: {
          mithril: Number(miningCore.powders?.["mithril"] ?? 0),
          gemstone: Number(miningCore.powders?.["gemstone"] ?? 0),
          glacite: Number(miningCore.powders?.["glacite"] ?? 0),
        },
        nodes,
      };
    }

    // Garden.
    const gardenRaw = member["garden"] as
      | {
          garden_experience?: number;
          crop_milestones?: Record<string, number>;
          visitors_served?: number;
          composts?: number;
        }
      | undefined;

    const garden: import("./skyblock").GardenStats | undefined = gardenRaw
      ? {
          level: computeSkill("FARMING", Number(gardenRaw.garden_experience ?? 0)).level,
          xp: Number(gardenRaw.garden_experience ?? 0),
          cropMilestones: Object.fromEntries(
            Object.entries(gardenRaw.crop_milestones ?? {})
              .filter(([, v]) => Number(v) > 0)
              .map(([k, v]) => [k.replace(/^CROP_/, "").toLowerCase(), Number(v)]),
          ),
          ...(Number(gardenRaw.visitors_served ?? 0) > 0
            ? { visitorsServed: Number(gardenRaw.visitors_served) }
            : {}),
          ...(Number(gardenRaw.composts ?? 0) > 0 ? { compost: Number(gardenRaw.composts) } : {}),
        }
      : undefined;

    // Crimson Isle (nether island): dojo, Kuudra, factions.
    const nether = member["nether_island_player_data"] as
      | {
          dojo?: Record<string, { player_score?: number }>;
          kuudra_completed_tiers?: Record<string, number>;
          matriarch?: Record<string, unknown>;
        }
      | undefined;

    const dojo: Record<string, number> = {};
    for (const [key, value] of Object.entries(nether?.dojo ?? {})) {
      const score = Number((value as { player_score?: number } | undefined)?.player_score ?? 0);
      if (score > 0) dojo[key.replace(/^dojo_|_time$|_success$/, "")] = score;
    }
    const kuudra: Record<string, number> = {};
    for (const [key, value] of Object.entries(nether?.kuudra_completed_tiers ?? {})) {
      if (Number(value) > 0) kuudra[key] = Number(value);
    }

    const crimson: import("./skyblock").CrimsonStats | undefined =
      Object.keys(dojo).length > 0 || Object.keys(kuudra).length > 0
        ? {
            dojo,
            kuudra,
            ...(typeof member["nether_faction"] === "string"
              ? { faction: titleCase(String(member["nether_faction"])) }
              : {}),
          }
        : undefined;

    // Rift.
    const riftRaw = member["rift"] as
      | {
          gallery?: Record<string, unknown>;
          castle?: Record<string, unknown>;
          village?: Record<string, unknown>;
          dead_cats?: Record<string, unknown>;
          serpent_bondmagic?: Record<string, unknown>;
          motes?: number;
        }
      | undefined;

    let rift: import("./skyblock").RiftStats | undefined;
    if (riftRaw) {
      const progress: Record<string, number> = {};
      for (const [section, value] of Object.entries(riftRaw)) {
        if (value && typeof value === "object") {
          for (const [key, v] of Object.entries(value as Record<string, unknown>)) {
            if (typeof v === "number" && v > 0) progress[`${section}_${key}`] = v;
          }
        }
      }
      if (Object.keys(progress).length > 0 || Number(riftRaw.motes ?? 0) > 0) {
        rift = {
          ...(Number(riftRaw.motes ?? 0) > 0 ? { motes: Number(riftRaw.motes) } : {}),
          progress,
        };
      }
    }

    // Museum (summary only — full contents need a separate call).
    const museumRaw = member["museum"] as
      | {
          items?: Record<string, unknown>;
          appraisal_date?: string;
        }
      | undefined;

    const museum: import("./skyblock").MuseumStats | undefined = museumRaw
      ? {
          donatedItems: Object.keys(museumRaw.items ?? {}).length,
          ...(museumRaw.appraisal_date ? { appraised: 1 } : {}),
        }
      : undefined;

    // Achievements.
    const achievementsRaw = member["achievements"] as Record<string, number> | undefined;

    let achievements: import("./skyblock").AchievementStats | undefined;
    if (achievementsRaw && Object.keys(achievementsRaw).length > 0) {
      const categories: Record<string, number> = {};
      let points = 0;
      for (const [key, value] of Object.entries(achievementsRaw)) {
        if (key.endsWith("_points")) {
          points += Number(value) || 0;
        } else if (Number(value) > 0) {
          categories[key.replace(/_/g, " ")] = Number(value);
        }
      }
      achievements = { points, categories };
    }

    // Jacob's farming contests.
    const jacobRaw = member["jacob2"] as
      | {
          medals_inv?: {
            bronze?: number;
            silver?: number;
            gold?: number;
            platinum?: number;
            diamond?: number;
          };
          per_crop?: Record<string, { best_contest?: number }>;
        }
      | undefined;

    const jacob: import("./skyblock").JacobStats | undefined = jacobRaw?.medals_inv
      ? {
          gold: Number(jacobRaw.medals_inv.gold ?? 0),
          silver: Number(jacobRaw.medals_inv.silver ?? 0),
          bronze: Number(jacobRaw.medals_inv.bronze ?? 0),
          ...(Number(jacobRaw.medals_inv.platinum ?? 0) > 0
            ? { platinum: Number(jacobRaw.medals_inv.platinum) }
            : {}),
          ...(Number(jacobRaw.medals_inv.diamond ?? 0) > 0
            ? { diamond: Number(jacobRaw.medals_inv.diamond) }
            : {}),
          perCrop: Object.fromEntries(
            Object.entries(jacobRaw.per_crop ?? {})
              .map(([crop, data]) => [
                crop.replace(/^CROP_/, "").toLowerCase(),
                Number(data?.best_contest ?? 0),
              ])
              .filter(([, v]) => Number(v) > 0),
          ),
        }
      : undefined;

    // Experimental table.
    const expRaw = member["experimentation"] as
      | {
          simulators?: Record<string, { claims?: Record<string, number> }>;
        }
      | undefined;

    let experimentation: import("./skyblock").ExperimentationStats | undefined;
    if (expRaw?.simulators) {
      const claims: Record<string, number> = {};
      for (const [sim, data] of Object.entries(expRaw.simulators)) {
        for (const [claim, count] of Object.entries(data.claims ?? {})) {
          if (Number(count) > 0) claims[`${sim}_${claim}`] = Number(count);
        }
      }
      if (Object.keys(claims).length > 0) experimentation = { claims };
    }

    // Lifetime stats.
    const statsRaw = member["stats"] as Record<string, number> | undefined;

    const lifetimeStats: import("./skyblock").LifetimeStats | undefined =
      statsRaw && (Number(statsRaw["kills"] ?? 0) > 0 || Number(statsRaw["deaths"] ?? 0) > 0)
        ? {
            ...(Number(statsRaw["kills"] ?? 0) > 0 ? { kills: Number(statsRaw["kills"]) } : {}),
            ...(Number(statsRaw["deaths"] ?? 0) > 0 ? { deaths: Number(statsRaw["deaths"]) } : {}),
          }
        : undefined;

    // Co-op community upgrades (profile level).
    const communityUpgradesRaw = chosen.community_upgrades as
      { upgrades?: Array<{ upgrade?: string; tier?: number }> } | undefined;

    const communityUpgrades = (communityUpgradesRaw?.upgrades ?? [])
      .filter((u) => u.upgrade)
      .map((u) => ({ upgrade: titleCase(String(u.upgrade)), level: Number(u.tier ?? 0) }));

    // Sacks counts decoder & valuation against live bazaar/NPC prices
    const sacksRaw = (member["sacks_counts"] ?? (member["inventory"] as Record<string, unknown> | undefined)?.["sacks_counts"] ?? {}) as Record<string, number>;
    let sacks: import("./skyblock").SacksData | undefined;
    const sackEntries = Object.entries(sacksRaw).filter(([, count]) => typeof count === "number" && count > 0);
    if (sackEntries.length > 0) {
      const bazaar = await getBazaar().catch(() => null);
      const bzMap = new Map<string, number>();
      for (const prod of bazaar?.products ?? []) {
        bzMap.set(prod.id, prod.sellPrice || prod.buyPrice || 0);
      }
      const itemsList = await getItems().catch(() => []);
      const itemMeta = new Map(itemsList.map((it) => [it.id, it]));
      const sackItems: import("./skyblock").SackItem[] = [];
      let totalSacksValue = 0;
      for (const [id, count] of sackEntries) {
        const unitPrice = bzMap.get(id) ?? (itemMeta.get(id)?.npcSell ?? 0);
        const val = Math.round(unitPrice * count);
        totalSacksValue += val;
        sackItems.push({
          id,
          name: names.get(id) ?? titleCase(id.replace(/_/g, " ")),
          count,
          value: val,
        });
      }
      sackItems.sort((a, b) => b.value - a.value);
      sacks = {
        totalValue: totalSacksValue,
        items: sackItems,
      };
    }

    const profile = member["profile"] as { last_save?: number } | undefined;
    const lastSaveRaw = member["last_save"];

    const payload = {
      username: name,
      uuid,

      profiles: summaries,

      activeProfileId: chosen.profile_id,

      skills,

      skillAverage: Math.round(skillAverage * 100) / 100,

      totalSkillXp: skills.reduce((sum, skill) => sum + skill.totalXp, 0),

      purse: Number(currencies?.coin_purse ?? 0),

      bank: typeof chosen.banking?.balance === "number" ? chosen.banking.balance : null,

      containers,

      collections,

      fairySouls: Number(fairySoul?.total_collected ?? 0),

      lastSave: Number(profile?.last_save ?? lastSaveRaw ?? Date.now()),

      ...(dungeons ? { dungeons } : {}),

      ...(slayers.length ? { slayers } : {}),

      ...(pets.length ? { pets } : {}),

      ...(hotm ? { hotm } : {}),

      ...(garden ? { garden } : {}),

      ...(crimson ? { crimson } : {}),

      ...(rift ? { rift } : {}),

      ...(museum ? { museum } : {}),

      ...(achievements ? { achievements } : {}),

      ...(jacob ? { jacob } : {}),

      ...(experimentation ? { experimentation } : {}),

      ...(lifetimeStats ? { lifetimeStats } : {}),

      ...(communityUpgrades.length ? { communityUpgrades } : {}),

      ...(sacks ? { sacks } : {}),
    };

    // Runtime-validate the normalized payload before it crosses the wire.
    const validated = validatePlayerData(payload);

    if (validated && !userKeyProvided) {
      profileCache.set(cacheKey, { at: Date.now(), data: validated });
    }

    return validated;
  } catch (err) {
    console.error("Error in getPlayerData:", err);

    return null;
  }
}
