/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuctionHouseRouteImport } from './routes/auction-house'
import { Route as BazaarRouteImport } from './routes/bazaar'
import { Route as BossesRouteImport } from './routes/bosses'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as CronSampleRouteImport } from './routes/cron-sample'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FlipsRouteImport } from './routes/flips'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MinionsRouteImport } from './routes/minions'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as WikiItemIdRouteImport } from './routes/wiki.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionHouseRoute = AuctionHouseRouteImport.update({
  id: '/auction-house',
  path: '/auction-house',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaarRoute = BazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const BossesRoute = BossesRouteImport.update({
  id: '/bosses',
  path: '/bosses',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const CronSampleRoute = CronSampleRouteImport.update({
  id: '/cron-sample',
  path: '/cron-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FlipsRoute = FlipsRouteImport.update({
  id: '/flips',
  path: '/flips',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MinionsRoute = MinionsRouteImport.update({
  id: '/minions',
  path: '/minions',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiItemIdRoute = WikiItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auction-house': typeof AuctionHouseRoute
  '/bazaar': typeof BazaarRoute
  '/bosses': typeof BossesRoute
  '/calendar': typeof CalendarRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/crafting': typeof CraftingRoute
  '/cron-sample': typeof CronSampleRoute
  '/dashboard': typeof DashboardRoute
  '/flips': typeof FlipsRoute
  '/garden': typeof GardenRoute
  '/goals': typeof GoalsRoute
  '/inventory': typeof InventoryRoute
  '/minions': typeof MinionsRoute
  '/net-worth': typeof NetWorthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/skills': typeof SkillsRoute
  '/wiki': typeof WikiRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$itemId': typeof WikiItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auction-house': typeof AuctionHouseRoute
  '/bazaar': typeof BazaarRoute
  '/bosses': typeof BossesRoute
  '/calendar': typeof CalendarRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/crafting': typeof CraftingRoute
  '/cron-sample': typeof CronSampleRoute
  '/dashboard': typeof DashboardRoute
  '/flips': typeof FlipsRoute
  '/garden': typeof GardenRoute
  '/goals': typeof GoalsRoute
  '/inventory': typeof InventoryRoute
  '/minions': typeof MinionsRoute
  '/net-worth': typeof NetWorthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/skills': typeof SkillsRoute
  '/wiki': typeof WikiRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$itemId': typeof WikiItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/auction-house': typeof AuctionHouseRoute
  '/bazaar': typeof BazaarRoute
  '/bosses': typeof BossesRoute
  '/calendar': typeof CalendarRoute
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/crafting': typeof CraftingRoute
  '/cron-sample': typeof CronSampleRoute
  '/dashboard': typeof DashboardRoute
  '/flips': typeof FlipsRoute
  '/garden': typeof GardenRoute
  '/goals': typeof GoalsRoute
  '/inventory': typeof InventoryRoute
  '/minions': typeof MinionsRoute
  '/net-worth': typeof NetWorthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/skills': typeof SkillsRoute
  '/wiki': typeof WikiRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/wiki/$itemId': typeof WikiItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisor'
    | '/analytics'
    | '/auction-house'
    | '/bazaar'
    | '/bosses'
    | '/calendar'
    | '/collections'
    | '/compare'
    | '/connect'
    | '/crafting'
    | '/cron-sample'
    | '/dashboard'
    | '/flips'
    | '/garden'
    | '/goals'
    | '/inventory'
    | '/minions'
    | '/net-worth'
    | '/notifications'
    | '/settings'
    | '/simulator'
    | '/skills'
    | '/wiki'
    | '/profile/$username'
    | '/wiki/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisor'
    | '/analytics'
    | '/auction-house'
    | '/bazaar'
    | '/bosses'
    | '/calendar'
    | '/collections'
    | '/compare'
    | '/connect'
    | '/crafting'
    | '/cron-sample'
    | '/dashboard'
    | '/flips'
    | '/garden'
    | '/goals'
    | '/inventory'
    | '/minions'
    | '/net-worth'
    | '/notifications'
    | '/settings'
    | '/simulator'
    | '/skills'
    | '/wiki'
    | '/profile/$username'
    | '/wiki/$itemId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisor'
    | '/analytics'
    | '/auction-house'
    | '/bazaar'
    | '/bosses'
    | '/calendar'
    | '/collections'
    | '/compare'
    | '/connect'
    | '/crafting'
    | '/cron-sample'
    | '/dashboard'
    | '/flips'
    | '/garden'
    | '/goals'
    | '/inventory'
    | '/minions'
    | '/net-worth'
    | '/notifications'
    | '/settings'
    | '/simulator'
    | '/skills'
    | '/wiki'
    | '/profile/$username'
    | '/wiki/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuctionHouseRoute: typeof AuctionHouseRoute
  BazaarRoute: typeof BazaarRoute
  BossesRoute: typeof BossesRoute
  CalendarRoute: typeof CalendarRoute
  CollectionsRoute: typeof CollectionsRoute
  CompareRoute: typeof CompareRoute
  ConnectRoute: typeof ConnectRoute
  CraftingRoute: typeof CraftingRoute
  CronSampleRoute: typeof CronSampleRoute
  DashboardRoute: typeof DashboardRoute
  FlipsRoute: typeof FlipsRoute
  GardenRoute: typeof GardenRoute
  GoalsRoute: typeof GoalsRoute
  InventoryRoute: typeof InventoryRoute
  MinionsRoute: typeof MinionsRoute
  NetWorthRoute: typeof NetWorthRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SkillsRoute: typeof SkillsRoute
  WikiRoute: typeof WikiRouteWithChildren
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction-house': {
      id: '/auction-house'
      path: '/auction-house'
      fullPath: '/auction-house'
      preLoaderRoute: typeof AuctionHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazaar': {
      id: '/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof BazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bosses': {
      id: '/bosses'
      path: '/bosses'
      fullPath: '/bosses'
      preLoaderRoute: typeof BossesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-sample': {
      id: '/cron-sample'
      path: '/cron-sample'
      fullPath: '/cron-sample'
      preLoaderRoute: typeof CronSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flips': {
      id: '/flips'
      path: '/flips'
      fullPath: '/flips'
      preLoaderRoute: typeof FlipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minions': {
      id: '/minions'
      path: '/minions'
      fullPath: '/minions'
      preLoaderRoute: typeof MinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$itemId': {
      id: '/wiki/$itemId'
      path: '/$itemId'
      fullPath: '/wiki/$itemId'
      preLoaderRoute: typeof WikiItemIdRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface WikiRouteChildren {
  WikiItemIdRoute: typeof WikiItemIdRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiItemIdRoute: WikiItemIdRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuctionHouseRoute: AuctionHouseRoute,
  BazaarRoute: BazaarRoute,
  BossesRoute: BossesRoute,
  CalendarRoute: CalendarRoute,
  CollectionsRoute: CollectionsRoute,
  CompareRoute: CompareRoute,
  ConnectRoute: ConnectRoute,
  CraftingRoute: CraftingRoute,
  CronSampleRoute: CronSampleRoute,
  DashboardRoute: DashboardRoute,
  FlipsRoute: FlipsRoute,
  GardenRoute: GardenRoute,
  GoalsRoute: GoalsRoute,
  InventoryRoute: InventoryRoute,
  MinionsRoute: MinionsRoute,
  NetWorthRoute: NetWorthRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SkillsRoute: SkillsRoute,
  WikiRoute: WikiRouteWithChildren,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
